# Generated by Django 3.2 on 2021-04-17 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='parameters',
        ),
    ]
