# Generated by Django 3.2 on 2021-04-17 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_service_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterInService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('checkbox', 'Чекбокс'), ('text', 'Текст'), ('number', 'Целое число')], help_text='Тип поля формы', max_length=8, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип параметра для услуги',
                'verbose_name_plural': 'Типы параметров для услуг',
                'ordering': ['type', 'parameter'],
            },
        ),
        migrations.RenameModel(
            old_name='ServiceParameter',
            new_name='Parameter',
        ),
        migrations.DeleteModel(
            name='ServiceParameterInService',
        ),
        migrations.AddField(
            model_name='parameterinservice',
            name='parameter',
            field=models.ForeignKey(help_text='Параметр, который задан для услуги', on_delete=django.db.models.deletion.CASCADE, related_name='services_assigned', to='orders.parameter', verbose_name='Параметр'),
        ),
        migrations.AddField(
            model_name='parameterinservice',
            name='service',
            field=models.ForeignKey(help_text='Услуга, для которой задан параметр', on_delete=django.db.models.deletion.CASCADE, related_name='parameters_assigned', to='orders.service', verbose_name='Услуга'),
        ),
        migrations.AddConstraint(
            model_name='parameterinservice',
            constraint=models.UniqueConstraint(fields=('service', 'parameter'), name='unique_parameter_in_service'),
        ),
    ]
