# Generated by Django 3.2 on 2021-04-17 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_auto_20210417_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='done',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Выполнено'),
        ),
        migrations.AddField(
            model_name='order',
            name='performed',
            field=models.ForeignKey(help_text='Сотрудник, выполнивший заказ', limit_choices_to=models.Q(is_staff=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_performed', to=settings.AUTH_USER_MODEL, verbose_name='Выполнил'),
        ),
        migrations.AlterField(
            model_name='order',
            name='author',
            field=models.ForeignKey(help_text='Автор заказа', limit_choices_to=models.Q(is_staff=False), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_issued', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
