# Generated by Django 3.2 on 2021-04-17 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_auto_20210417_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='done',
            new_name='complete',
        ),
        migrations.RemoveField(
            model_name='order',
            name='performed',
        ),
        migrations.AddField(
            model_name='order',
            name='performer',
            field=models.ForeignKey(help_text='Исполнитель заказа', limit_choices_to=models.Q(is_staff=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_performed', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
    ]
